module.exports = {
	basic: {
		'./Assets/Js/MbiConfig.js': function(fs, fd, done) {

			var grunt = require('grunt'),
				file = grunt.file.read('./Assets/Config/Config.json'),
				text = '/**\n * this file gets created automatically from config.json on grunt build!\n * if you need to change values, edit ./Assets/Config/Config.json\n *\n * DO NOT EDIT THIS FILE!\n */\n\n';

			text += 'define([], function() {\n\nvar config = ';
			text += file;
			text += ';\n';
			text += 'config.modules = { MbiConfig : true };\n';
			text += 'return config;\n\n});\n\n/* DO NOT EDIT THIS FILE */'

			fs.writeSync(fd, text);
			done();

		}
	}
};